.TH AURUMCOIN-CLI "1" "February 2016" "aurumcoin-cli 0.12"
.SH NAME
aurumcoin-cli \- a remote procedure call client for Aurumcoin Core. 
.SH SYNOPSIS
aurumcoin-cli [options] <command> [params] \- Send command to Aurumcoin Core. 
.TP
aurumcoin-cli [options] help \- Asks Aurumcoin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the aurumcoin-cli program. aurumcoin-cli is an RPC client used to send commands to Aurumcoin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBaurumcoind\fP, \fBaurumcoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
